INSERT INTO [dbo].[Demo] ([Job_Id], [Job_Name], [C_Id], [Payment], [V_Id]) VALUES (NULL, NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Job_Assignment] ([Job_Id], [Job_Name], [C_Id], [Payment], [V_Id]) VALUES (1, N'Website Design', 1, CAST(5000.00 AS Decimal(18, 2)), 1)
INSERT INTO [dbo].[Job_Assignment] ([Job_Id], [Job_Name], [C_Id], [Payment], [V_Id]) VALUES (2, N'Graphic Design', 2, CAST(3500.50 AS Decimal(18, 2)), NULL)
INSERT INTO [dbo].[Job_Assignment] ([Job_Id], [Job_Name], [C_Id], [Payment], [V_Id]) VALUES (3, N'Office Cleaning', 3, CAST(1200.00 AS Decimal(18, 2)), NULL)
INSERT INTO [dbo].[Job_Assignment] ([Job_Id], [Job_Name], [C_Id], [Payment], [V_Id]) VALUES (4, N'Social Media Setup', 4, CAST(4500.00 AS Decimal(18, 2)), NULL)
INSERT INTO [dbo].[Job_Assignment] ([Job_Id], [Job_Name], [C_Id], [Payment], [V_Id]) VALUES (5, N'Document Filing', 5, CAST(800.00 AS Decimal(18, 2)), NULL)
INSERT INTO [dbo].[Job_Assignment] ([Job_Id], [Job_Name], [C_Id], [Payment], [V_Id]) VALUES (6, N'Event Planning', 6, CAST(7000.00 AS Decimal(18, 2)), NULL)
INSERT INTO [dbo].[Job_Assignment] ([Job_Id], [Job_Name], [C_Id], [Payment], [V_Id]) VALUES (7, N'Marketing Research', 7, CAST(2500.00 AS Decimal(18, 2)), NULL)
INSERT INTO [dbo].[Job_Assignment] ([Job_Id], [Job_Name], [C_Id], [Payment], [V_Id]) VALUES (8, N'Product Photography', 8, CAST(3200.00 AS Decimal(18, 2)), NULL)
INSERT INTO [dbo].[Job_Assignment] ([Job_Id], [Job_Name], [C_Id], [Payment], [V_Id]) VALUES (9, N'Inventory Audit', 9, CAST(1500.00 AS Decimal(18, 2)), NULL)
INSERT INTO [dbo].[Job_Assignment] ([Job_Id], [Job_Name], [C_Id], [Payment], [V_Id]) VALUES (10, N'Customer Support', 10, CAST(1800.00 AS Decimal(18, 2)), NULL)
INSERT INTO [dbo].[Job_Assignment] ([Job_Id], [Job_Name], [C_Id], [Payment], [V_Id]) VALUES (11, N'Newsletter Design', 11, CAST(2200.00 AS Decimal(18, 2)), NULL)
INSERT INTO [dbo].[Job_Assignment] ([Job_Id], [Job_Name], [C_Id], [Payment], [V_Id]) VALUES (12, N'Packing & Delivery', 12, CAST(1000.00 AS Decimal(18, 2)), NULL)
INSERT INTO [dbo].[Job_Assignment] ([Job_Id], [Job_Name], [C_Id], [Payment], [V_Id]) VALUES (13, N'Research Report', 13, CAST(4000.00 AS Decimal(18, 2)), NULL)
INSERT INTO [dbo].[Job_Assignment] ([Job_Id], [Job_Name], [C_Id], [Payment], [V_Id]) VALUES (14, N'Website Maintenance', 14, CAST(3000.00 AS Decimal(18, 2)), 2)
INSERT INTO [dbo].[Job_Assignment] ([Job_Id], [Job_Name], [C_Id], [Payment], [V_Id]) VALUES (15, N'Social Media Campaign', 15, CAST(3500.00 AS Decimal(18, 2)), 1)
INSERT INTO [dbo].[Job_Assignment] ([Job_Id], [Job_Name], [C_Id], [Payment], [V_Id]) VALUES (16, N'Event Photography', 16, CAST(2800.00 AS Decimal(18, 2)), 1)
INSERT INTO [dbo].[Job_Assignment] ([Job_Id], [Job_Name], [C_Id], [Payment], [V_Id]) VALUES (17, N'Teaching Session', 17, CAST(2000.00 AS Decimal(18, 2)), 4)
INSERT INTO [dbo].[Job_Assignment] ([Job_Id], [Job_Name], [C_Id], [Payment], [V_Id]) VALUES (18, N'Document Verification', 18, CAST(1500.00 AS Decimal(18, 2)), 5)
INSERT INTO [dbo].[Job_Assignment] ([Job_Id], [Job_Name], [C_Id], [Payment], [V_Id]) VALUES (19, N'Health Checkup', 19, CAST(2500.00 AS Decimal(18, 2)), 7)
INSERT INTO [dbo].[Job_Assignment] ([Job_Id], [Job_Name], [C_Id], [Payment], [V_Id]) VALUES (20, N'Community Survey', 20, CAST(3000.00 AS Decimal(18, 2)), 1)
